package singleton

import (
	"context"
	"github.com/romanornr/autodealer/dealer"
	"github.com/stretchr/testify/mock"
)

// MockDealerBuilder is an autogenerated mock type for the Dealer
type MockDealerBuilder struct {
	mock.Mock
}

type MockDealer struct {
	dealer.Dealer
	mock.Mock
}

func (m *MockDealerBuilder) Build(ctx context.Context) (*dealer.Dealer, error) {
	args := m.Called()
	return args.Get(0).(*dealer.Dealer), args.Error(1)
}
